### ISSUE TITLE
swift tutorial => OHMySQLContainer.shared() doesn't work

### ISSUE THREAD

**Issue by xiaosean** [oleghnidets/OHMySQL#10]
## What did you do?

The following line of code in the tutorial doesn't work!
It is swift version in the select part 

`let response = try? OHMySQLContainer.shared().mainQueryContext?.executeQueryRequestAndFetchResult(query)`

shared() will cause compile error!
Hint:
Cannot call value of non-function type 'OHMySQLContainer' 
Replace '()' with ''

## What happened instead?

If i use the following line, 
It can compile but no response.

             let response = try?OHMySQLContainer.shared.mainQueryContext?.executeQueryRequestAndFetchResult(query)

Now, I use the following line, can use!

`              let response = try? context.executeQueryRequestAndFetchResult(query)`

But i don't think it is a well behavior.

## What did you expect?

Please revise the tutorial, thanks!

## OHMySQL Environment

- **OHMySQL version:**2.1.3
- **Xcode version:**9.2
- **Swift version:** *(if applicable, if not remove)*4.03
- **Platform(s) running OHMySQL:**ios

**Comment by oleghnidets** [comment]
Thanks for reporting. 
I will revise all related documentation.

**Comment by oleghnidets** [comment]
Done! 🍻

**Comment by estella98** [comment]
Thank you @xiaosean  so much. My friend and I have been trying to fix this issue for a long time until we see your post. and we have browsed all the documentations and still see the old, wrong request. are you sure you update it? @oleghnidets

**Comment by oleghnidets** [comment]
@estella98 My bad. But I guess Xcode' auto-completed should help write a code. Don't you use Xcode?

**Comment by estella98** [comment]
I do use Xcode. but it does not give me any auto finish recommendation as usual when I am using ohmysql.
